### ISSUE TITLE
Command fails with "Error: invalid field: files." when testing vs PHP 8 or higher

### ISSUE THREAD

**Issue by PatonLewis** [danielbachhuber/php-compat-command#19]
The title explains it. Please see the screenshot for an example:

<img width="457" alt="Screenshot 2023-07-03 at 5 59 11 PM" src="https://github.com/danielbachhuber/php-compat-command/assets/2848889/1c600972-e5dc-465b-acc5-17e699ddac9d">

Edited to add: All of the tested versions of PHP are available on the host. I'm using WordPress 6.2.2 (the current version as of this writing), and WP-CLI 2.7.1

**Comment by danielbachhuber** [comment]
@PatonLewis Thanks for the report! I can reproduce it. I'll fix this up when I have a moment.
